// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RabbitaskWebAPI.Data;

#nullable disable

namespace RabbitaskWebAPI.Migrations
{
    [DbContext(typeof(RabbitaskContext))]
    [Migration("20251103000638_SeedInitialData")]
    partial class SeedInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RabbitaskWebAPI.Models.Anexo", b =>
                {
                    b.Property<int>("CdAnexo")
                        .HasColumnType("int")
                        .HasColumnName("cd_anexo");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int")
                        .HasColumnName("cd_tarefa");

                    b.Property<string>("NmCaminhoAnexo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nm_caminho_anexo");

                    b.HasKey("CdAnexo", "CdUsuario", "CdTarefa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdUsuario", "CdTarefa" }, "fk_anexo_tarefa");

                    b.ToTable("anexo");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.CodigoConexao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_expiracao");

                    b.Property<bool>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("usado");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CdUsuario")
                        .HasDatabaseName("idx_codigo_conexao_usuario");

                    b.HasIndex("Codigo")
                        .HasDatabaseName("idx_codigo_conexao_codigo");

                    b.ToTable("codigo_conexao", (string)null);
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.ConexaoUsuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdUsuarioAgente")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario_agente");

                    b.HasKey("CdUsuario", "CdUsuarioAgente")
                        .HasName("PRIMARY");

                    b.HasIndex("CdUsuarioAgente")
                        .HasDatabaseName("fk_conexao_usuario_agente_usuario");

                    b.ToTable("conexao_usuario", (string)null);
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Prioridade", b =>
                {
                    b.Property<int>("CdPrioridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_prioridade");

                    b.Property<string>("NmPrioridade")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_prioridade");

                    b.HasKey("CdPrioridade")
                        .HasName("PRIMARY");

                    b.ToTable("prioridade");

                    b.HasData(
                        new
                        {
                            CdPrioridade = 1,
                            NmPrioridade = "Super Alta"
                        },
                        new
                        {
                            CdPrioridade = 2,
                            NmPrioridade = "Alta"
                        },
                        new
                        {
                            CdPrioridade = 3,
                            NmPrioridade = "Média Alta"
                        },
                        new
                        {
                            CdPrioridade = 4,
                            NmPrioridade = "Média"
                        },
                        new
                        {
                            CdPrioridade = 5,
                            NmPrioridade = "Média Baixa"
                        },
                        new
                        {
                            CdPrioridade = 6,
                            NmPrioridade = "Baixa"
                        },
                        new
                        {
                            CdPrioridade = 7,
                            NmPrioridade = "Super Baixa"
                        });
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Tag", b =>
                {
                    b.Property<int>("CdTag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_tag");

                    b.Property<string>("NmTag")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_tag");

                    b.HasKey("CdTag")
                        .HasName("PRIMARY");

                    b.ToTable("tag");

                    b.HasData(
                        new
                        {
                            CdTag = 1,
                            NmTag = "Escolar"
                        },
                        new
                        {
                            CdTag = 2,
                            NmTag = "Escola"
                        },
                        new
                        {
                            CdTag = 3,
                            NmTag = "Português"
                        },
                        new
                        {
                            CdTag = 4,
                            NmTag = "Matemática"
                        },
                        new
                        {
                            CdTag = 5,
                            NmTag = "Inglês"
                        },
                        new
                        {
                            CdTag = 6,
                            NmTag = "Geografia"
                        },
                        new
                        {
                            CdTag = 7,
                            NmTag = "Espanhol"
                        },
                        new
                        {
                            CdTag = 8,
                            NmTag = "Filosofia"
                        },
                        new
                        {
                            CdTag = 9,
                            NmTag = "Casa"
                        },
                        new
                        {
                            CdTag = 10,
                            NmTag = "Trabalho"
                        },
                        new
                        {
                            CdTag = 11,
                            NmTag = "Trabalho Escolar"
                        },
                        new
                        {
                            CdTag = 12,
                            NmTag = "Lição de Casa"
                        },
                        new
                        {
                            CdTag = 13,
                            NmTag = "Limpeza da Casa"
                        },
                        new
                        {
                            CdTag = 14,
                            NmTag = "Extras"
                        },
                        new
                        {
                            CdTag = 15,
                            NmTag = "Extra"
                        },
                        new
                        {
                            CdTag = 16,
                            NmTag = "Sociologia"
                        },
                        new
                        {
                            CdTag = 17,
                            NmTag = "Biologia"
                        },
                        new
                        {
                            CdTag = 18,
                            NmTag = "Física"
                        });
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int")
                        .HasColumnName("cd_tarefa");

                    b.Property<int?>("CdPrioridade")
                        .HasColumnType("int")
                        .HasColumnName("cd_prioridade");

                    b.Property<int?>("CdUsuarioProprietario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario_proprietario");

                    b.Property<string>("DsTarefa")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ds_tarefa");

                    b.Property<DateTime?>("DtConclusao")
                        .HasColumnType("datetime")
                        .HasColumnName("dt_conclusao");

                    b.Property<DateTime?>("DtCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("dt_criacao");

                    b.Property<DateTime?>("DtPrazo")
                        .HasColumnType("datetime")
                        .HasColumnName("dt_prazo");

                    b.Property<string>("NmTarefa")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_tarefa");

                    b.HasKey("CdUsuario", "CdTarefa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdPrioridade" }, "fk_tarefa_prioridade");

                    b.HasIndex(new[] { "CdUsuarioProprietario" }, "fk_tarefa_usuario_proprietario");

                    b.ToTable("tarefa");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TarefaFeedback", b =>
                {
                    b.Property<int>("CdTipoSentimento")
                        .HasColumnType("int")
                        .HasColumnName("cd_tipo_sentimento");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int")
                        .HasColumnName("cd_tarefa");

                    b.Property<string>("DsFeedback")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("ds_feedback");

                    b.HasKey("CdTipoSentimento", "CdUsuario", "CdTarefa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdUsuario", "CdTarefa" }, "fk_tarefa_feedback_tarefa");

                    b.ToTable("tarefa_feedback");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TipoSentimento", b =>
                {
                    b.Property<int>("CdTipoSentimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_tipo_sentimento");

                    b.Property<string>("NmTipoSentimento")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_tipo_sentimento");

                    b.HasKey("CdTipoSentimento")
                        .HasName("PRIMARY");

                    b.ToTable("tipo_sentimento");

                    b.HasData(
                        new
                        {
                            CdTipoSentimento = 1,
                            NmTipoSentimento = "Satisfação"
                        },
                        new
                        {
                            CdTipoSentimento = 2,
                            NmTipoSentimento = "Confiança"
                        },
                        new
                        {
                            CdTipoSentimento = 3,
                            NmTipoSentimento = "Surpresa"
                        },
                        new
                        {
                            CdTipoSentimento = 4,
                            NmTipoSentimento = "Alegria"
                        },
                        new
                        {
                            CdTipoSentimento = 5,
                            NmTipoSentimento = "Felicidade"
                        },
                        new
                        {
                            CdTipoSentimento = 6,
                            NmTipoSentimento = "Gratidão"
                        },
                        new
                        {
                            CdTipoSentimento = 7,
                            NmTipoSentimento = "Orgulho"
                        },
                        new
                        {
                            CdTipoSentimento = 8,
                            NmTipoSentimento = "Inspiração"
                        },
                        new
                        {
                            CdTipoSentimento = 9,
                            NmTipoSentimento = "Apreciação"
                        },
                        new
                        {
                            CdTipoSentimento = 10,
                            NmTipoSentimento = "Aprovação"
                        },
                        new
                        {
                            CdTipoSentimento = 11,
                            NmTipoSentimento = "Curiosidade"
                        },
                        new
                        {
                            CdTipoSentimento = 12,
                            NmTipoSentimento = "Dúvida"
                        },
                        new
                        {
                            CdTipoSentimento = 13,
                            NmTipoSentimento = "Confusão"
                        },
                        new
                        {
                            CdTipoSentimento = 14,
                            NmTipoSentimento = "Desapontamento"
                        },
                        new
                        {
                            CdTipoSentimento = 15,
                            NmTipoSentimento = "Frustração"
                        },
                        new
                        {
                            CdTipoSentimento = 16,
                            NmTipoSentimento = "Preocupação"
                        },
                        new
                        {
                            CdTipoSentimento = 17,
                            NmTipoSentimento = "Desaprovação"
                        },
                        new
                        {
                            CdTipoSentimento = 18,
                            NmTipoSentimento = "Decepção"
                        },
                        new
                        {
                            CdTipoSentimento = 19,
                            NmTipoSentimento = "Aversão"
                        });
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TipoUsuario", b =>
                {
                    b.Property<int>("CdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_tipo_usuario");

                    b.Property<string>("NmTipoUsuario")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_tipo_usuario");

                    b.HasKey("CdTipoUsuario")
                        .HasName("PRIMARY");

                    b.ToTable("tipo_usuario");

                    b.HasData(
                        new
                        {
                            CdTipoUsuario = 1,
                            NmTipoUsuario = "Usuário Comum"
                        },
                        new
                        {
                            CdTipoUsuario = 2,
                            NmTipoUsuario = "Agente"
                        });
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Topico", b =>
                {
                    b.Property<int>("CdTopico")
                        .HasColumnType("int")
                        .HasColumnName("cd_topico");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int")
                        .HasColumnName("cd_tarefa");

                    b.Property<bool?>("IcConcluido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ic_concluido");

                    b.Property<string>("NmTopico")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("nm_topico");

                    b.HasKey("CdTopico", "CdUsuario", "CdTarefa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdUsuario", "CdTarefa" }, "fk_topico_tarefa");

                    b.ToTable("topico");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Usuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<string>("CdTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("cd_telefone");

                    b.Property<int?>("CdTipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_tipo_usuario");

                    b.Property<string>("NmEmail")
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("nm_email");

                    b.Property<string>("NmSenha")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nm_senha");

                    b.Property<string>("NmUsuario")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("nm_usuario");

                    b.HasKey("CdUsuario")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdTipoUsuario" }, "fk_usuario_tipo_usuario");

                    b.HasIndex(new[] { "NmEmail" }, "nm_email")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("TagTarefa", b =>
                {
                    b.Property<int>("CdTag")
                        .HasColumnType("int");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int");

                    b.HasKey("CdTag", "CdUsuario", "CdTarefa");

                    b.ToTable("TagTarefa");
                });

            modelBuilder.Entity("TarefaTag", b =>
                {
                    b.Property<int>("CdTag")
                        .HasColumnType("int")
                        .HasColumnName("cd_tag");

                    b.Property<int>("CdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("cd_usuario");

                    b.Property<int>("CdTarefa")
                        .HasColumnType("int")
                        .HasColumnName("cd_tarefa");

                    b.HasKey("CdTag", "CdUsuario", "CdTarefa")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CdUsuario", "CdTarefa" }, "fk_tarefa_tag_tarefa");

                    b.ToTable("tarefa_tag", (string)null);
                });

            modelBuilder.Entity("UsuarioUsuario", b =>
                {
                    b.Property<int>("CdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("CdUsuarioAgente")
                        .HasColumnType("int");

                    b.HasKey("CdUsuario", "CdUsuarioAgente");

                    b.HasIndex("CdUsuarioAgente");

                    b.ToTable("UsuarioUsuario");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Anexo", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Tarefa", "Cd")
                        .WithMany("Anexos")
                        .HasForeignKey("CdUsuario", "CdTarefa")
                        .IsRequired()
                        .HasConstraintName("fk_anexo_tarefa");

                    b.Navigation("Cd");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.CodigoConexao", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("CdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_codigo_conexao_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.ConexaoUsuario", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Usuario", "CdUsuarioNavigation")
                        .WithMany()
                        .HasForeignKey("CdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_conexao_usuario_usuario");

                    b.HasOne("RabbitaskWebAPI.Models.Usuario", "CdUsuarioAgenteNavigation")
                        .WithMany()
                        .HasForeignKey("CdUsuarioAgente")
                        .IsRequired()
                        .HasConstraintName("fk_conexao_usuario_agente_usuario");

                    b.Navigation("CdUsuarioAgenteNavigation");

                    b.Navigation("CdUsuarioNavigation");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Tarefa", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Prioridade", "CdPrioridadeNavigation")
                        .WithMany("Tarefas")
                        .HasForeignKey("CdPrioridade")
                        .HasConstraintName("fk_tarefa_prioridade");

                    b.HasOne("RabbitaskWebAPI.Models.Usuario", "CdUsuarioNavigation")
                        .WithMany("TarefaCdUsuarioNavigations")
                        .HasForeignKey("CdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_usuario");

                    b.HasOne("RabbitaskWebAPI.Models.Usuario", "CdUsuarioProprietarioNavigation")
                        .WithMany("TarefaCdUsuarioProprietarioNavigations")
                        .HasForeignKey("CdUsuarioProprietario")
                        .HasConstraintName("fk_tarefa_usuario_proprietario");

                    b.Navigation("CdPrioridadeNavigation");

                    b.Navigation("CdUsuarioNavigation");

                    b.Navigation("CdUsuarioProprietarioNavigation");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TarefaFeedback", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.TipoSentimento", "CdTipoSentimentoNavigation")
                        .WithMany("TarefaFeedbacks")
                        .HasForeignKey("CdTipoSentimento")
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_feedback_tipo_sentimento");

                    b.HasOne("RabbitaskWebAPI.Models.Tarefa", "Cd")
                        .WithMany("TarefaFeedbacks")
                        .HasForeignKey("CdUsuario", "CdTarefa")
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_feedback_tarefa");

                    b.Navigation("Cd");

                    b.Navigation("CdTipoSentimentoNavigation");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Topico", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Tarefa", "Cd")
                        .WithMany("Topicos")
                        .HasForeignKey("CdUsuario", "CdTarefa")
                        .IsRequired()
                        .HasConstraintName("fk_topico_tarefa");

                    b.Navigation("Cd");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Usuario", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.TipoUsuario", "CdTipoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("CdTipoUsuario")
                        .HasConstraintName("fk_usuario_tipo_usuario");

                    b.Navigation("CdTipoUsuarioNavigation");
                });

            modelBuilder.Entity("TarefaTag", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("CdTag")
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_tag_tag");

                    b.HasOne("RabbitaskWebAPI.Models.Tarefa", null)
                        .WithMany()
                        .HasForeignKey("CdUsuario", "CdTarefa")
                        .IsRequired()
                        .HasConstraintName("fk_tarefa_tag_tarefa");
                });

            modelBuilder.Entity("UsuarioUsuario", b =>
                {
                    b.HasOne("RabbitaskWebAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RabbitaskWebAPI.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CdUsuarioAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Prioridade", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Tarefa", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("TarefaFeedbacks");

                    b.Navigation("Topicos");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TipoSentimento", b =>
                {
                    b.Navigation("TarefaFeedbacks");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("RabbitaskWebAPI.Models.Usuario", b =>
                {
                    b.Navigation("TarefaCdUsuarioNavigations");

                    b.Navigation("TarefaCdUsuarioProprietarioNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
